[package]
authors = ["Brian Anderson <banderson@mozilla.com>"]
description = "Test your Rust markdown documentation via Cargo"
license = "MIT/Apache-2.0"
name = "skeptic"
repository = "https://github.com/brson/rust-skeptic"
version = "0.12.3"

[dependencies]
pulldown-cmark = "0.1.0"
tempdir = "0.3.5"
glob = "0.2"
walkdir = "1.0"
serde = "1.0.11"
serde_derive = "1.0.11"
serde_json = "1.0.2"
toml = "0.4.4"
bytecount = "0.1.7"

[dev-dependencies]
unindent = "0.1.0"

[dependencies.error-chain]
version = "0.10.0"
default-features = false

[lib]
name = "skeptic"
path = "lib.rs"
